# **Part - 2 Project -> Adtech_Fraud_detection_Analysis**

# **DATA ASSESSING & CLEANING**

In [1]:
import pandas as pd

In [2]:
#load data
df3 = pd.read_parquet('clicks_messy.parquet')
df4 = pd.read_parquet('installs.parquet')
df5 = pd.read_parquet('revenue.parquet')

1. CLICKS DATASET

### Clicks Table Summary

The Clicks table represents the raw advertising traffic generated from mobile ad campaigns.  
Each row corresponds to a single ad click event when a user interacts with an advertisement displayed on a publisher platform.

This table forms the foundation of the analytics pipeline because every install and revenue event originates from a click.

**Columns Description**

- **click_id** – Unique identifier for each click event.
- **campaign_id** – Identifier for the advertising campaign responsible for generating the click.
- **publisher_id** – Identifier for the publisher or platform where the advertisement was displayed.
- **user_id** – Unique identifier representing the user who clicked on the advertisement.
- **device_type** – Type of device used by the user (e.g., Android, iOS).
- **country** – Geographic location of the user at the time of the click.
- **ip_address** – IP address of the user device, useful for detecting suspicious traffic or bot activity.
- **timestamp** – Date and time when the click occurred.
- **cost** – Advertising cost associated with the click.

The Clicks table is the largest table in the dataset and contains intentionally introduced data issues such as missing values, duplicate records, and abnormal patterns to simulate real-world advertising traffic.

In [3]:
df3.head()

,click_id,campaign_id,publisher_id,user_id,device_type,country,cost,timestamp,ip_address
0,1,150,83,406708,Android,US,0.300000,2024-03-01 18:22:42,48.47.128.218
1,2,136,57,902009,iOS,Germany,0.513611,2024-09-16 11:43:17,21.64.38.117
2,3,26,33,595169,Android,India,0.200000,2024-09-23 09:00:55,207.241.26.48
3,4,105,5,675095,iOS,None,0.480000,2024-11-17 04:07:10,168.210.213.174
4,5,23,94,112516,Android,India,0.290000,2024-08-18 04:57:58,149.240.238.164

In [4]:
print(df3.shape)
print(df3.info())
print(df3.describe())
print(df3.dtypes)
print(df3.duplicated().sum())
print(df3.isnull().sum())

(5005000, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5005000 entries, 0 to 5004999
Data columns (total 9 columns):
 #   Column        Dtype
---  ------        -----
 0   click_id      int64
 1   campaign_id   int64
 2   publisher_id  int64
 3   user_id       int64
 4   device_type   object
 5   country       object
 6   cost          float64
 7   timestamp     datetime64[ns]
 8   ip_address    object
dtypes: datetime64[ns](1), float64(1), int64(4), object(3)
memory usage: 343.7+ MB
None
           click_id   campaign_id  publisher_id       user_id          cost  \
count  5.005000e+06  5.005000e+06  5.005000e+06  5.005000e+06  5.005000e+06
mean   2.499997e+06  1.004655e+02  5.048390e+01  4.999215e+05  2.741231e-01
min    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00  1.000000e-02
25%    1.249992e+06  5.000000e+01  2.500000e+01  2.498600e+05  1.400000e-01
50%    2.500016e+06  1.000000e+02  5.000000e+01  4.998160e+05  2.700000e-01
75%    3.749992e+06  1.500000e+02  7.500000e+01  7.499730e+05  4.000000e-01
max    5.000000e+06  2.000000e+02  1.000000e+02  1.000000e+06  6.266690e+00
std    1.443372e+06  5.773703e+01  2.886321e+01  2.886806e+05  2.100241e-01

                           timestamp
count                        5005000
mean   2024-07-01 05:57:20.873989376
min              2024-01-01 00:00:02
25%    2024-04-01 23:00:20.750000128
50%       2024-06-30 00:08:01.500000
75%    2024-09-29 23:56:21.750000128
max              2024-12-30 23:59:46
std                              NaN
click_id                 int64
campaign_id              int64
publisher_id             int64
user_id                  int64
device_type             object
country                 object
cost                   float64
timestamp       datetime64[ns]
ip_address              object
dtype: object
4997
click_id            0
campaign_id         0
publisher_id        0
user_id             0
device_type     50376
country         99915
cost                0
timestamp           0
ip_address          0
dtype: int64

1. dataset have duplicates = 4990
2. have missing values in device_type and country
3. casing issue like android & ANDROID
4. Cost outliers

In [5]:
df3 = df3.drop_duplicates()

In [6]:
df3.duplicated().sum()

np.int64(0)

In [7]:
print(df3.shape)

(5000003, 9)

In [8]:
df3["device_type"] = df3["device_type"].fillna("unknown")
df3["country"] = df3["country"].fillna("unknown")

In [9]:
df3.isnull().sum()

click_id        0
campaign_id     0
publisher_id    0
user_id         0
device_type     0
country         0
cost            0
timestamp       0
ip_address      0
dtype: int64

In [10]:
df3["device_type"] = df3["device_type"].str.lower()

In [11]:
df3["country"] = df3["country"].str.lower()

In [12]:
df3['country'].unique()

array(['us', 'germany', 'india', 'unknown', 'uk', 'canada', 'usa'],
      dtype=object)

In [13]:
print(df3[df3['country'] == 'usa'].shape)
print(df3[df3['country'] == 'us'].shape)

(8000, 9)
(978491, 9)

In [14]:
df3["country"] = df3["country"].replace("us", "usa")

In [15]:
df3["country"].value_counts()

country
usa        986491
germany    979410
uk         978666
canada     978204
india      977401
unknown     99831
Name: count, dtype: int64

In [16]:
df3["cost"].describe()

count    5.000003e+06
mean     2.741241e-01
std      2.100764e-01
min      1.000000e-02
25%      1.400000e-01
50%      2.700000e-01
75%      4.000000e-01
max      6.266690e+00
Name: cost, dtype: float64

In [17]:
df3[df3["cost"] > 2] #outliers

,click_id,campaign_id,publisher_id,user_id,device_type,country,cost,timestamp,ip_address
1323,1324,92,51,618235,android,india,6.26669,2024-11-19 12:56:42,54.176.35.105
5020,5021,100,25,189296,android,canada,6.26669,2024-10-31 11:42:41,49.123.171.121
5376,5377,17,15,715487,tablet,uk,6.26669,2024-04-06 19:59:28,29.199.160.168
7001,7002,87,94,758680,android,india,6.26669,2024-04-12 18:08:11,149.147.68.233
9436,9437,79,7,277018,ios,india,6.26669,2024-09-17 07:58:27,174.90.87.48
...,...,...,...,...,...,...,...,...,...
4998838,4998839,155,90,965441,android,india,6.26669,2024-10-17 20:15:21,173.131.2.72
4999198,4999199,43,61,538326,android,germany,6.26669,2024-03-14 11:49:25,109.32.78.8
4999864,4999865,44,10,68802,android,india,6.26669,2024-02-25 23:55:39,194.46.26.19
5000733,2660852,68,69,383933,android,germany,6.26669,2024-05-01 22:52:22,120.227.17.60
5002424,1270779,172,8,240653,android,usa,6.26669,2024-09-18 11:31:08,210.249.187.184

In [18]:
df3 = df3[df3["cost"] < 2]

In [19]:
df3[df3["cost"] > 2]

Empty DataFrame
Columns: [click_id, campaign_id, publisher_id, user_id, device_type, country, cost, timestamp, ip_address]
Index: []

In [20]:
df3.to_parquet('clicks_cleaned.parquet', index=False)

In [21]:
df3.to_csv('clicks_cleaned.csv', index=False)

# **2. Intsall Dataset**

### Installs Table Summary

The Installs table captures app installation events that occur after users click on advertisements.  
Each row represents a successful app install attributed to a specific ad click.

This table is used to measure the effectiveness of advertising campaigns by linking user installs to the clicks that generated them. It plays a crucial role in conversion analysis and campaign performance evaluation.

**Columns Description**

- **install_id** – Unique identifier for each installation event.
- **click_id** – Identifier of the click event that led to the installation. This column links the install to the Clicks table for attribution analysis.
- **install_timestamp** – The exact date and time when the application was installed by the user.

The installs table enables analysts to track user conversion from click to install and helps evaluate campaign efficiency, publisher performance, and user acquisition effectiveness.

In [22]:
print(df4.shape)
print(df4.info())
print(df4.describe())
print(df4.dtypes)
print(df4.duplicated().sum())
print(df4.isnull().sum())

(250000, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 3 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   install_id         250000 non-null  int64
 1   click_id           250000 non-null  int64
 2   install_timestamp  250000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(2)
memory usage: 5.7 MB
None
          install_id      click_id              install_timestamp
count  250000.000000  2.500000e+05                         250000
mean   125000.500000  2.498441e+06  2024-07-01 08:45:39.930696192
min         1.000000  5.800000e+01            2024-01-01 00:13:14
25%     62500.750000  1.245044e+06            2024-04-01 04:42:23
50%    125000.500000  2.501212e+06            2024-07-01 09:01:48
75%    187500.250000  3.750475e+06  2024-09-30 12:44:07.249999872
max    250000.000000  4.999917e+06            2024-12-31 00:48:27
std     72168.927986  1.445046e+06                            NaN
install_id                    int64
click_id                      int64
install_timestamp    datetime64[ns]
dtype: object
0
install_id           0
click_id             0
install_timestamp    0
dtype: int64

All Clean - no need to do anything

# **3. Revenue Dataset**

### Revenue Table Summary

The Revenue table records monetization events generated by users after installing the application.  
Each row represents a revenue-generating action performed by a user, such as an in-app purchase or ad interaction.

This table is essential for evaluating the financial performance of advertising campaigns because it links user activity to revenue generation. By connecting this table with the Clicks and Installs tables, analysts can measure metrics such as campaign profitability, user lifetime value (LTV), and return on ad spend (ROAS).

**Columns Description**

- **user_id** – Unique identifier of the user who generated the revenue event.
- **revenue** – The monetary value generated from the user action.
- **event_timestamp** – The date and time when the revenue event occurred.

The Revenue table allows analysts to track how acquired users generate value over time and helps businesses understand which campaigns and publishers bring the most profitable users.

In [23]:
df5.head()

   user_id  revenue     event_timestamp    event_type
0      374     2.38 2024-09-20 06:31:33      purchase
1   947335    35.02 2024-02-13 07:51:47      purchase
2   904215    21.05 2024-11-19 23:11:00  subscription
3   362117    18.09 2024-07-31 11:10:49      purchase
4   246216     9.66 2024-07-16 22:07:00  subscription

In [24]:
print(df5.shape)
print(df5.info())
print(df5.describe())
print(df5.dtypes)
print(df5.duplicated().sum())
print(df5.isnull().sum())

(100000, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   user_id          100000 non-null  int64
 1   revenue          100000 non-null  float64
 2   event_timestamp  100000 non-null  datetime64[ns]
 3   event_type       100000 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 3.1+ MB
None
             user_id        revenue                event_timestamp
count  100000.000000  100000.000000                         100000
mean   499653.624230      19.975217  2024-07-01 12:05:17.260810240
min        13.000000       0.000000            2024-01-01 00:04:22
25%    249757.000000       5.760000            2024-04-01 09:27:14
50%    499168.000000      13.840000     2024-07-01 04:38:56.500000
75%    749220.750000      27.780000  2024-10-01 00:10:00.750000128
max    999991.000000     261.910000            2024-12-30 23:52:53
std    288514.560263      19.903422                            NaN
user_id                     int64
revenue                   float64
event_timestamp    datetime64[ns]
event_type                 object
dtype: object
0
user_id            0
revenue            0
event_timestamp    0
event_type         0
dtype: int64

In [25]:
df5['event_type'].value_counts()

event_type
purchase        33521
ad_view         33312
subscription    33167
Name: count, dtype: int64

All Clean - No need to do anything